### ISSUE TITLE
Frontend Developer Experience

### ISSUE THREAD

**Issue by wbprice** [Code4HR/okcandidate-platform#118]
cc @kaxcode @beetalogist @stanzheng @BretFisher 

At the moment, the developer experience for a front-end developer isn't great.  When using `docker` to run the project in development mode, it takes a long time for changes in templates to be reflected in the app.  How can we improve this?

**Comment by BretFisher** [comment]
After taking a look, here are some goals/tasking I'll try to get done this week:

1. file watcher that's fast at rebuilding when needed locally
2. remove proxy from being used for local dev. It's only needed for prod and some limited proxy testing by ops on occasion.
3. Goal: Nothing needed by new dev other then `docker-compose up`. 
4. Remove .env to reduce developer complexity and prevent env var bleeding into unnecessary containers (e.g, node keys in db container). Move those vars to compose file var and secrets.
5. Implement secrets in compose (compose file 3.1 format).
6. Update to compose 3.1 format to support secrets and swarm stacks in prod.
7. default docker-compose.yml is designed for local dev ease-of-use. Any other overrides can be added in other files for CI or Prod.
8. Use node+docker best practices like in https://github.com/BretFisher/node-docker-good-defaults
9. always pin versions in dockerfile when possible (node 6.10)
11. store node image in code4hr org and keep it up to date with latest node 6.10 (it rebuilds when upstream node repo changes)

**Comment by rydente** [comment]
Hey @BretFisher, I made a second issue to track these as subtasks.  If you have time to help out, cool, otherwise, I'm going to try and do what I can to help out with this as well, even if in baby steps.
