### ISSUE TITLE
Survey Progress Bar

### ISSUE THREAD

**Issue by wbprice** [Code4HR/okcandidate-platform#203]
Similar in function to: 
![blizzard-progress-bar](https://user-images.githubusercontent.com/2590422/29231351-e3de9c8e-7eb4-11e7-8844-cfa05f2ba293.jpg)

Minimum number of questions answered is displayed as a tick between start and finish.  Button to right becomes active when minimum number of questions are answered.

**Comment by kmcurry** [comment]
Thankfully, not with that aesthetic! 😉
