### ISSUE TITLE
Wire up Facebook share button

### ISSUE THREAD

**Issue by wbprice** [Code4HR/okcandidate-platform#217]
<img width="347" alt="screen shot 2017-08-15 at 12 08 49 pm" src="https://user-images.githubusercontent.com/2590422/29371657-f25bd748-8276-11e7-9f02-f01597db63d0.png">

Each social media bar is associated with a specific candidate.  When the user clicks the Facebook icon, it should open a "Share with Facebook" browser tab with prefilled text related to the specific candidate.

**Comment by qwo** [comment]
weird this shows it was merged so i presume this is closed.
