### ISSUE TITLE
Dockerize the platform

### ISSUE THREAD

**Issue by ttavenner** [Code4HR/okcandidate-platform#60]
Make it easy to set the platform up by running a single command. Look at the Dockerfile from [OKCandidate V1](https://github.com/Code4HR/okcandidate) as an example.

**Comment by rydente** [comment]
Merged in #76, but looks like we could use some simplification and improvements.  Would we want to wait before those get implemented before we close this out or should we create another issue to track that?

**Comment by ttavenner** [comment]
Improvements are being tracked in #118
