### ISSUE TITLE
Ecosystem: Question card

### ISSUE THREAD

**Issue by ttavenner** [Code4HR/okcandidate-platform#67]
Displays info button icon molecule, category icon atom, question text organism, intensity input organism, next button icon molecule, skip button icon molecule.

**Comment by wbprice** [comment]
<img width="419" alt="screen shot 2017-04-15 at 12 11 03 pm" src="https://cloud.githubusercontent.com/assets/2590422/25065010/c3d85f8e-21d4-11e7-8e7d-9f58f323b4bc.png">

**Comment by rydente** [comment]
Part of #109.

**Comment by ttavenner** [comment]
Resolved in #91
