### ISSUE TITLE
Molecule: Affinity Selector

### ISSUE THREAD

**Issue by kaxcode** [Code4HR/okcandidate-platform#88]
Displays a series of 5 hearts. When the user clicks on the heart, the hearts up to and including the heart clicked are highlighted.

**Comment by wbprice** [comment]
![screen shot 2017-04-21 at 2 54 06 pm](https://cloud.githubusercontent.com/assets/2590422/25292147/e670c0b8-26a2-11e7-8acd-3db5f083e2f4.png)

Replace the placeholder text in `SurveyCard` with the rating component you guys selected.

**Comment by ttavenner** [comment]
Resolved by #109
