### ISSUE TITLE
Linting

### ISSUE THREAD

**Issue by rydente** [Code4HR/okcandidate-platform#95]
@wbprice may I lint now? :3

**Comment by wbprice** [comment]
Sure.  The linting rules are not going to change and it would be good to nail this down.

**Comment by rydente** [comment]
Cool, on it now.

One question: I see several properties not yet typed via `PropTypes`, including nested ones.  How do you want to handle those?

**Comment by wbprice** [comment]
If it's clear what prop type checking function needs to be used for a given prop, go ahead and put iti n.  If you have any questions let me know.

**Comment by rydente** [comment]
PR #96

**Comment by ttavenner** [comment]
I was just working on this. Glad you tackled it first. I am setting up Codeship right now and the first test run failed utterly because of linting.

**Comment by rydente** [comment]
\o/!

**Comment by rydente** [comment]
Closing!
